version: "3.9"
services:
  chat-manager:
    build: .
    ports:
      - "8080:8080"
    links:
      - rabbitmq
      - mongodb
    depends_on:
      - rabbitmq
      - mongodb
    command: sh -c "/wait && /build/chat-manager.go"
    environment:
      - WAIT_HOSTS=rabbitmq:5672,mongodb:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
  stock-bot:
    build: ./docker/projects/stock-bot
    ports:
      - "8090:8080"
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    command: sh -c "/wait && /build/stock-bot.go"
    environment:
      - WAIT_HOSTS=rabbitmq:5672
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
  rabbitmq:
    build: ./docker/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
  mongodb:
    build: ./docker/mongo
    ports:
      - "27017:27017"
    expose:
      - 27017
    